Iter3
chazari-x/shortens-URLs pull request #3
Opened 2023-03-07 14:25 UTC by chazari-x

2023-03-09 22:28 UTC, tmvrus requested changes
Есть недочеты

2023-03-09 22:28 UTC, tmvrus commented on internal/app/server/server.go
> +	if err := http.ListenAndServe(":8080", r); err != nil {
http.ListenAndServe всегда возвращет ошибку, об этом написано в документации к методу, рекомендую ознакомиться, что бы понимать при каких ошибках не стоит вызывать Fatal

2023-03-09 22:28 UTC, tmvrus commented on internal/app/server/server_test.go
> +func testRequest(t *testing.T, ts *httptest.Server, method, path, body string) (int, string) {
для таких ф-й предусмотрен метод t.Helper что бы не вызывать путаницу в репортах

2023-03-09 22:28 UTC, tmvrus commented on internal/app/storage/storage.go
> +var sURLs = make(map[string]string)
у такого подхода есть недостаток: нельзя работать больше чем с 1 экземпляром storage

2023-03-09 22:28 UTC, tmvrus commented on internal/pkg/shortens/shortens.go
> +}
это очень слабый алгоритм, для aa.ru и bb.ru будут одинаковые ID, стоит использовать что-то более серьезное

2023-03-09 22:28 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +	b, _ := io.ReadAll(r.Body)
эту ошибку нужно как минимум проверить и логировать

2023-03-09 22:28 UTC, tmvrus commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusBadRequest)
если добавить тут return то ниже else можно не писать, это улучшит читаемость

2023-03-09 22:28 UTC, tmvrus commented on internal/app/server/server.go
> +	r.Get("/*", handlers.Get)
chi позволяет использовать параметры {name} в роутах, и обращаться к ним в хендлерах, этой возможностью нужно пользоваться иначе нет никакого смысла использовать фреймворк

2023-03-10 06:38 UTC, chazari-x commented on internal/pkg/shortens/shortens.go
> +}
ID **aa.ru** не будет равен ID **bb.ru**, так как **n** - это кол-во элементов в хранилище

Если **aa.ru** добавить в хранилище первым, то у него будет **ID = 0**. 
А у **bb.ru** не может быть ID = 0, так как он добавлен в хранилище вторым и **ID = 1**.

2023-03-10 09:56 UTC, tmvrus commented on internal/pkg/shortens/shortens.go
> +}
Так эта ф-я ничего не знает ни про какое хранилище, она делает то что делает.

2023-03-14 21:02 UTC, tmvrus approved these changes

2023-03-16 18:26 UTC, merged